"""empty message

Revision ID: 8dedc058177b
Revises: 6d900f231c39
Create Date: 2018-04-13 14:43:53.523883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8dedc058177b'
down_revision = '6d900f231c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkout', 'Date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkout', 'Date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
